# Submit for plots for figures 
#S1, S2, and S6a were generated by Tom van der Valk and therefore are not included in this script
# Figures 1b, 3b, S3a, S3b, and S3c are generated below from comparing MQ in simulated datasets

# To generate AMBER plots for figures in paper

# running AMBER

for fig in 1a 2a 2b 3a 3c 4a 4b S4a S4b S4c S5 S6b ; do

  path=...your parent directory.../AMBER/figures_plots
  
  mkdir -p ${path}
  
  if [ $fig == "2a" ] || [ $fig == "2b" ] || [ $fig == "3c" ] || [ $fig == "4b" ] || [ $fig == "S4a" ] || [ $fig == "S4b" ] || [ $fig == "S4c" ] || [ $fig == "S6b" ] || ; then
  
      ../AMBER --bamfiles ${path}/fig${fig}.tsv --output ${path}/fig${fig} --errorbars --counts
  
  elif [ $fig == "3a" ]
  
      ../AMBER --bamfiles ${path}/fig${fig}.tsv --output ${path}/fig${fig} --errorbars --counts --exclude exclude.txt
  
  elif [ $fig == "1a" ]
  
      ../AMBER --bamfiles ${path}/fig${fig}.tsv --output ${path}/fig${fig} --errorbars --exclude exclude.txt
      
  else
  
      ../AMBER --bamfiles ${path}/fig${fig}.tsv --output ${path}/fig${fig} --errorbars 
      
  fi

done


# Submit for all simulated rhino and elephant libraries to look at MQ comparisons

for species in elephant rhino ; do 

  for div in 0 1 2 3 4 5 6 9 12 15 ; do 

    for quality in 100end 50end 10end 1end ; do

      for mapper in bwaaln bwamem sensitive_bowtie verysensitive_bowtie local_bowtie ; do
  
        MQ_tsv_path=...your parent directory.../AMBER/${mapper}_tsv/div${div}_tsv
        MQ_plot_path=...your parent directory.../AMBER/plots/${mapper}_${species}_plots_by_MQ
        
        mkdir -p ${MQ_plot_path}
        
        # running AMBER
        
        ./AMBER --bamfiles ${MQ_tsv_path}/${mapper}_${species}_div${div}_${quality}_by_MQ.tsv --output ${MQ_plot_path}/${mapper}_${species}_div${div}_${quality}_by_MQ --errorbars --counts 

      done

    done

  done

done
